@echo off
echo === SimonFX cleanup starting ===

:: Remove legacy Java/Kotlin starter code
if exist app\src\main\java\com\example (
    rmdir /s /q app\src\main\java\com\example
    echo Removed legacy package: app\src\main\java\com\example
)

:: Remove nav drawer menu XMLs
del /q app\src\main\res\menu\activity_main_drawer.xml 2>nul
del /q app\src\main\res\menu\main.xml 2>nul

:: Remove nav header/layout XMLs
del /q app\src\main\res\layout\nav_header_main.xml 2>nul
del /q app\src\main\res\layout\app_bar_main.xml 2>nul
del /q app\src\main\res\layout\content_main.xml 2>nul

:: Remove drawable icons generated by template
del /q app\src\main\res\drawable\ic_menu_*.xml 2>nul

echo === SimonFX cleanup complete ===
pause
